apiVersion: v1
kind: Service
metadata:
  name: {{ default (printf "%s-postgres" (include "typebotio.fullname" .)) .Values.typebot_db.service.nameOverride }}
  labels:
    {{- include "typebotio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.typebot_db.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.typebot_db.service.port }}
      targetPort: 5432
  selector:
    {{- include "typebotio.selectorLabels" . | nindent 4 }}
    katenary.v3/component: typebot_db