{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "glpi.fullname" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.certManager.enabled }}
    {{- if eq .Values.certManager.issuerKind "ClusterIssuer" }}
    cert-manager.io/cluster-issuer: {{ .Values.certManager.issuerName | quote }}
    {{- else }}
    cert-manager.io/issuer: {{ .Values.certManager.issuerName | quote }}
    {{- end }}
    {{- if .Values.certManager.http01EditInPlace }}
    acme.cert-manager.io/http01-edit-in-place: "true"
    {{- end }}
    {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}

  {{- /* TLS: use ingress.tls if set; otherwise build from form fields */ -}}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName | quote }}
      {{- end }}
    {{- end }}
  {{- else if and .Values.ingressForm.tls.enabled .Values.ingressForm.host }}
  tls:
    - hosts:
        - {{ .Values.ingressForm.host | quote }}
      {{- if .Values.ingressForm.tls.secretName }}
      secretName: {{ .Values.ingressForm.tls.secretName | quote }}
      {{- end }}
  {{- end }}

  rules:
    {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ include "glpi.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
    {{- else if .Values.ingressForm.host }}
    - host: {{ .Values.ingressForm.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingressForm.path | quote }}
            pathType: {{ .Values.ingressForm.pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ include "glpi.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
    {{- end }}
{{- end }}
